### ISSUE TITLE
[Feature] Banner

### ISSUE THREAD

**Issue by Major-Eth** [Major-Eth/yearn-web-lib#4]
# What
Create a basic `<Banner />` component.

## Requirements
- The component should be a `<section>` and accept any default props (`<section [...] {...props}`)
- The component should contain a `Heading 2` with color set to `theme.primary`
- The component should contain a `Body Regular` text with color set to `theme.primary`
- The component should have a border set to `theme.primary`
- The component should have a background set to `theme.background-variant`
- The component should support the 3 basic themes: `light`, `dark` and `blue`. This should be abstracted and send as props.

## Ressources
[Figma](https://www.figma.com/file/bFN3UFHtXuOwDMeml3GgKV/yearn-polished?node-id=1265%3A8769)

## Notes
Name of colors are subject to changes

**Comment by karelianpie** [comment]
Will work on this issue tomorrow
