### ISSUE TITLE
[Feature] Icons

### ISSUE THREAD

**Issue by Major-Eth** [Major-Eth/yearn-web-lib#5]
# What
Create a basic bunch of `<Icons />` component.

## Requirements
- The component should be a `<svg>` exported from Figma and support at least `className` and `style`.
- The svg should use `currentcolor` instead of fixed color to use the one set in the css
- The chevrons and arrows should not be duplicated (only one and then use code-rotation)
- Icons should fit in a 24x24px box

## Ressources
[Figma](https://www.figma.com/file/bFN3UFHtXuOwDMeml3GgKV/yearn-polished?node-id=1265%3A8769)

**Comment by karelianpie** [comment]
I will pick this one next, already added a few icons with [the ](https://github.com/Major-Eth/yearn-web-lib/pull/17)

Great minds think alike, did the following for the `Chevron` icon, it seems the best way

> The chevrons and arrows should not be duplicated (only one and then use code-rotation)

I am not so sure about the props (e.g. `currentcolor` and `className`), maybe we can discuss that a bit, but it's not a blocker to get this work started.
